

//Crear un botón en HTML y usar JavaScript para mostrar un mensaje cuando se hace clic.
let button = document.createElement("button");
button.innerText = " Haz Click";
documen.body.appendChild(button);

//Cambiar el contenido de un elemento HTML mediante JavaScript.
document.getElementById("SOY UN BOTON");

//Ocultar y mostrar elementos HTML utilizando JavaScript.

function ocultar() {
  document.getElementById("SOY UN BOTON");
  style.display = "none";
}

function mostrar() {
  document.getElementById("SOY UN BOTON");
  style.display = "block";
}

// Crear un array de 10 nombres.//

cosnt salad = ["tomate", lechuga,]